#!/bin/sh

# Run clang-format
clang-format ./include/**/*.hh -i -Werror -n || exit 1
clang-format ./src/*.cc -i -Werror -n || exit 1
clang-format ./tests/**/*.hh -i -Werror -n || exit 1
clang-format ./tests/**/*.cc -i -Werror -n || exit 1

# Run cpplint
cpplint --quiet --recursive . || exit 1

exit 0
