#!/bin/sh

# Run clang-format
clang-format ./include/**/*.hpp -i -Werror -n || exit 1
clang-format ./src/*.cpp -i -Werror -n || exit 1
clang-format ./tests/**/*.hpp -i -Werror -n || exit 1
clang-format ./tests/**/*.cpp -i -Werror -n || exit 1

# Run cpplint
cpplint --quiet --recursive . || exit 1

exit 0
