#ifndef POAC_OPTS_INSTALL_HPP
#define POAC_OPTS_INSTALL_HPP

#include <iostream>
#include <vector>
#include <string>
#include <string_view>
#include <fstream>
#include <map>
#include <regex>
#include <optional>

#include <boost/filesystem.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <yaml-cpp/yaml.h>

#include <poac/io.hpp>
#include <poac/core/except.hpp>
#include <poac/core/resolver/resolve.hpp>
#include <poac/core/resolver/lock.hpp>
#include <poac/util/argparse.hpp>
#include <poac/util/shell.hpp>

namespace poac::opts::install {
    constexpr auto summary = termcolor2::make_string("Install packages");
    constexpr auto options = termcolor2::make_string("-v | --verbose, -q | --quite, [args]");

    struct Options {
        bool quite;
        bool verbose;
        std::vector<std::string> package_list;
    };

    void stream_deps(YAML::Emitter& out, const core::resolver::resolve::Activated& deps) {
        out << YAML::Key << "dependencies";
        out << YAML::Value << YAML::BeginMap;

        for (const auto& dep : deps) {
            out << YAML::Key << dep.name;
            out << YAML::Value << YAML::BeginMap;

            out << YAML::Key << "version";
            out << YAML::Value << dep.version;

            out << YAML::Key << "source";
            out << YAML::Value << dep.source;

            if (!dep.deps.empty()) {
                stream_deps(out, dep.deps);
            }
            out << YAML::EndMap;
        }
        out << YAML::EndMap;
    }

    void create_lock_file(const std::string& timestamp, const core::resolver::resolve::Activated& activated_deps) {
        // Create a poac.lock
        if (std::ofstream ofs("poac.lock"); ofs) {
            ofs << "# Please do not edit this file.\n";
            YAML::Emitter out;
            out << YAML::BeginMap;

            out << YAML::Key << "timestamp";
            out << YAML::Value << timestamp;

            stream_deps(out, activated_deps);
            ofs << out.c_str() << '\n';
        }
    }

    // Copy package to ./deps
    bool copy_to_current(const std::string& from, const std::string& to) {
        const auto from_path = io::path::poac_cache_dir / from;
        const auto to_path = io::path::current_deps_dir / to;
        return io::path::recursive_copy(from_path, to_path);
    }

    void echo_install_status(const bool res, const std::string& n, const std::string& v, const std::string& s) {
        const std::string status = n + " " + v + " (from: " + s + ")";
        std::cout << '\r' << io::term::clr_line
                  << (res ? io::term::fetched : io::term::fetch_failed) << status << std::endl;
    }

    void fetch_packages( // TODO: そもそも関数が長くてキモい．
            const core::resolver::resolve::Backtracked& deps,
            const bool quite,
            const bool verbose)
    {
        namespace resolve = core::resolver::resolve;

        int exists_count = 0;
        for (const auto& [name, dep] : deps) {
            const auto cache_name = core::name::to_cache(dep.source, name, dep.version);
            const auto current_name = core::name::to_current(dep.source, name, dep.version);
            const bool is_cached = resolve::cache::resolve(cache_name);

            if (verbose) {
                std::cout << "NAME: " << name << "\n"
                          << "  VERSION: " <<  dep.version << "\n"
                          << "  SOURCE: " << dep.source << "\n"
                          << "  CACHE_NAME: " << cache_name << "\n"
                          << "  CURRENT_NAME: " << current_name << "\n"
                          << "  IS_CACHED: " << is_cached << "\n"
                          << std::endl;
            }

            if (resolve::current::resolve(current_name)) {
                ++exists_count;
                continue;
            }
            else if (is_cached) {
                const bool res = copy_to_current(cache_name, current_name);
                if (!quite) {
                    echo_install_status(res, name, dep.version, dep.source);
                }
            }
            else if (dep.source == "poac") {
                const auto pkg_dir = io::path::poac_cache_dir / cache_name;
                const auto tar_dir = pkg_dir.string() + ".tar.gz";
                const std::string target = resolve::archive_url(name, dep.version);

                { // Get archive file
                    std::ofstream output_file(tar_dir, std::ios::out | std::ios::binary);
                    const io::net::requests req{ POAC_API_HOST };
                    req.get(target, {}, std::move(output_file));
                }
                // If res is true, does not execute func. (short-circuit evaluation)
                bool result = io::tar::extract_spec_rm(tar_dir, pkg_dir);
                result = result && copy_to_current(cache_name, current_name);

                if (!quite) {
                    echo_install_status(result, name, dep.version, dep.source);
                }
            }
            else if (dep.source == "github") {
                util::shell clone_cmd = resolve::github::clone_command(name, dep.version);
                clone_cmd += (io::path::poac_cache_dir / cache_name).string();
                clone_cmd = clone_cmd.to_dev_null().stderr_to_stdout();

                bool result = clone_cmd.exec().has_value(); // true == error
                result = !result && copy_to_current(cache_name, current_name);

                if (!quite) {
                    echo_install_status(result, name, dep.version, dep.source);
                }
            }
            else {
                // If called this, it is a bug.
                throw core::except::error("Unexcepted error");
            }
        }
        if (exists_count == static_cast<int>(deps.size())) {
            std::cout << io::term::warning << "Already installed" << std::endl;
        }
    }

    core::resolver::resolve::Deps
    resolve_packages(const std::map<std::string, std::string>& dependencies) {
        namespace resolve = core::resolver::resolve;

        resolve::Deps deps;

        // Even if a package of the same name is written, it is excluded.
        // However, it can not deal with duplication of other information (e.g. version etc.).
        for (const auto& [name, interval] : dependencies) { // TODO: sourceはGitHubのみになる！！-> core::nameも要・修正
            // itr->first: itr->second
            const auto [source, parsed_name] = core::name::get_source(name);

            if (source == "poac" || source == "github") { // TODO: 不要
                deps.push_back({ {parsed_name}, {interval}, {source} });
            }
            else { // unknown source
                throw core::except::error("Unknown source");
            }
        }
        return deps;
    }

    core::resolver::resolve::Package<core::resolver::resolve::Name, core::resolver::resolve::Interval, core::resolver::resolve::Source>
    parse_arg_package(const std::string& v) {
        core::name::validate_package_name(v);

        const std::string NAME = "([a-z|\\d|\\-|_|\\/]*)";
        std::smatch match;
        if (std::regex_match(v, std::regex("^" + NAME + "$"))) { // TODO: 厳しくする
            const auto [source, parsed_name] = core::name::get_source(v);
            return { {parsed_name}, {"latest"}, {source} };
        }
        else if (std::regex_match(v, match, std::regex("^" + NAME + "=(.*)$"))) {
            const auto name = match[1].str();
            const auto [source, parsed_name] = core::name::get_source(name);
            const auto interval = match[2].str();
            return { {parsed_name}, {interval}, {source} };
        }
        else {
            throw core::except::error("Invalid arguments");
        }
    }

    std::string convert_to_interval(const std::string& version) {
        semver::Version upper(version); // TODO: semverのincrement methodを使う
        upper.major += 1;
        upper.minor = 0;
        upper.patch = 0;
        return ">=" + version + " and <" + upper.get_version();
    }

    [[nodiscard]] std::optional<core::except::Error>
    install(std::optional<io::yaml::Config>&& config, install::Options&& opts) {
        namespace fs = boost::filesystem;
        namespace resolve = core::resolver::resolve;

        fs::create_directories(io::path::poac_cache_dir);
        std::string timestamp = io::yaml::load_timestamp();

        // load lock file
        resolve::Resolved resolved_deps{};
        bool load_lock = false;
        if (opts.package_list.empty()) { // 引数からの指定が無い時，poac.ymlからしか読まないことになるため，lockファイルを読む．
            if (const auto locked_deps = core::resolver::lock::load(timestamp)) {
                resolved_deps = locked_deps.value();
                load_lock = true;
            }
        }

        // YAML::Node -> resolver:Deps
        resolve::Deps deps;
        for (const auto& v : opts.package_list) {
            deps.push_back(parse_arg_package(v));
        }
        if (!load_lock) {
            if (const auto dependencies = config->dependencies) { // io::yaml::get<std::map<std::string, YAML::Node>>(node, "deps")
                const auto resolved_packages = resolve_packages(dependencies.value());
                deps.insert(deps.end(), resolved_packages.begin(), resolved_packages.end());
            }
            else if (opts.package_list.empty()) { // 引数から指定しておらず(poac install)，poac.ymlにdeps keyが存在しない
                return core::except::Error::General{
                        "Required key `deps` does not exist in poac.yml.\n"
                        "Please refer to https://doc.poac.pm"
                };
            }
        }

        // resolve dependency
        if (!opts.quite) {
            std::cout << io::term::status << "Resolving dependencies..." << std::endl;
        }
        if (!load_lock) {
            resolved_deps = resolve::resolve(deps);
        }

        // download packages
        if (!opts.quite) {
            std::cout << io::term::status << "Fetching..." << std::endl;
            std::cout << std::endl;
        }
        fs::create_directories(io::path::current_deps_dir);
        fetch_packages(resolved_deps.backtracked, opts.quite, opts.verbose);
        if (!opts.quite) {
            std::cout << std::endl;
            io::term::status_done();
        }

        // TODO: Rewrite poac.yml
//        bool fix_yml = false;
//        for (const auto& d : deps) {
//            if (d.interval == "latest") {
//                node["deps"][d.name] = convert_to_interval(resolved_deps.backtracked[d.name].version);
//                fix_yml = true;
//            }
//        }
//        if (!opts.package_list.empty()) {
//            fix_yml = true;
//            for (const auto& d : deps) {
//                if (d.interval != "latest") {
//                    node["deps"][d.name] = d.interval;
//                }
//            }
//        }
//        if (fix_yml) {
//            if (std::ofstream ofs("poac.yml"); ofs) {
//                ofs << node;
//            }
//            timestamp = io::yaml::load_timestamp();
//        }

        if (!load_lock) {
            create_lock_file(timestamp, resolved_deps.activated);
        }

        return std::nullopt;
    }

    [[nodiscard]] std::optional<core::except::Error>
    exec(std::optional<io::yaml::Config>&& config, std::vector<std::string>&& args) {
        install::Options opts{};
        opts.quite = util::argparse::use_rm(args, "-q", "--quite");
        opts.verbose = util::argparse::use_rm(args, "-v", "--verbose") && !opts.quite;
        args.shrink_to_fit();
        opts.package_list = args;
        return install::install(std::move(config), std::move(opts));
    }
} // end namespace
#endif // !POAC_OPTS_INSTALL_HPP
