#!/bin/bash
set -e

isin () { for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done; return 1; }
topin () { for e in "${@:2}"; do [[ "${e::1}" == "$1" ]] && return 0; done; return 1; }

declare -a flags=('help' 'version')
declare -a subcommands=('init' 'new' 'install')

count=`echo -n $1 | sed -e 's/[^-]//g' | wc -c | awk '{print $0-1}'`

# Long flag.
if [[ $count == 2 ]] && `isin "${1//-}" "${flags[@]}"`; then
	exec "${CPM_ROOT}/lib/cpm-$1"
# Short flag.
elif [[ $count == 1 && ${#1} == 2 ]] && `topin "${1:1}" "${flags[@]}"`; then
	exec `find "${CPM_ROOT}/lib" -name "cpm--$1*"`
# Sub command.
elif [[ $count == 0 ]] && `isin "$1" "${subcommands[@]}"`; then
	exec "${CPM_ROOT}/lib/cpm-$1" "${@:2}"
# Other.
else
	echo "cpm: illegal option -- $@"
	exec "${CPM_ROOT}/lib/cpm---help"
fi
