#!/bin/bash
#
# Summary: install hoge
#
set -e

subcommand=${0##*/cpm-}
if [[ "$1" == '--help' || "$1" == '-h' ]]; then
	exec "${CPM_ROOT}/lib/cpm--help" $subcommand 'None'
elif [[ "$@" =~ '-' ]]; then
	echo "cpm ${subcommand}: illegal option -- $@"
	exec "${CPM_ROOT}/lib/cpm--help" $subcommand 'None'
else
	echo 'done.'
fi
