#!/bin/bash
#
# Summary: install hoge
#
set -e

filename=${0##*/cpm-}
if [[ "$1" == '--help' || "$1" == '-h' ]]; then
	exec "${CPM_ROOT}/lib/cpm--help" $filename 'None'
elif [[ "$@" =~ '-' ]]; then
	echo "cpm ${filename}: illegal option -- $@"
	exec "${CPM_ROOT}/lib/cpm--help" $filename 'None'
else
	echo 'done.'
fi
