#!/bin/bash
#
# Summary: neww hoge
#
set -e

subcommand=${0##*/cpm-}
if [[ "$1" == '--help' || "$1" == '-h' ]]; then
	exec "${CPM_ROOT}/lib/cpm--help" $subcommand 0
elif [[ "$#" -ge 1 ]]; then
	echo "cpm ${subcommand}: illegal option -- $@"
	exec "${CPM_ROOT}/lib/cpm--help" $subcommand 0
else
	echo 'done.'
fi
