#!/bin/bash
#
# Summary: Display help for a command.
#
set -e

# lib内の，cpm以外のファイルをparseする．
print_docs () {
	for filename in `find $1 -maxdepth 1 -type f -name 'cpm-*'`; do
		printf "   %-9s   %s\n" ${filename##*/cpm-} "`grep "# Summary: " ${filename} | head -1 | awk -F ": " '{print $2}'`"
	done
}

if [[ -z "$1" ]]; then
	echo 'Usage: cpm <command> [<args>]'
	echo
	echo 'Available commands:'
	print_docs "${CPM_ROOT}/lib"
	echo
	echo 'See `cpm <command> --help` for information on a specific command.'
	echo 'For full documentation, see: https://github.com/pocpm/cpm#readme'
else
	echo "Usage: cpm $1 $2"
fi
