#!/bin/bash
#
# Summary: Display help for a command.
# Options: []
#
set -e

# lib内の，poac以外のファイルをparseする．
print_docs () {
	for filename in `find $1 -maxdepth 1 -type f -name 'poac-*'`; do
		printf "   %-9s   %s\n" ${filename##*/poac-} "`grep "# Summary: " ${filename} | head -1 | awk -F ": " '{print $2}'`"
	done
}

if [[ -z "$1" ]]; then
	echo 'Usage: poac <command> [<args>]'
	echo
	echo 'Available commands:'
	print_docs "${POAC_ROOT}/lib"
	echo
	echo 'See `poac <command> --help` for information on a specific command.'
	echo 'For full documentation, see: https://github.com/poacpm/poac#readme'
else
	echo "Usage: poac $1 `grep "# Options: " "${POAC_ROOT}/lib/poac-$1" | head -1 | awk -F ": " '{print $2}'`"
fi
