#!/bin/bash
#
# Summary: Create a new project.
# Options: <project-name>
#
set -e

subcommand=${0##*/poac-}
if [[ "$1" == '--help' || "$1" == '-h' ]]; then
	exec "${POAC_ROOT}/lib/poac---help" $subcommand
elif [[ "$#" != 1 ]]; then
	echo "poac ${subcommand}: illegal option -- $@"
	exec "${POAC_ROOT}/lib/poac---help" $subcommand
else
	mkdir -v $1 1>/dev/null 2>/dev/null || \
	printf "\e[32mThe directory \"$1\" already exists.\e[m\n\n"
	cp -i ${POAC_ROOT}/tmpl/* ${POAC_ROOT}/tmpl/.[^\.]* ./$1 && \
	echo && \
	echo "Your \"$1\" project was created successfully." && \
	echo && \
	echo && \
	echo "Go into your project by running:" && \
	echo "    $ cd $1" && \
	echo && \
	echo "Start your project with:" && \
	echo "    $ poac main.cpp" && \
	echo
fi
