#ifndef POAC_UTIL_FTEMPLATE_HPP
#define POAC_UTIL_FTEMPLATE_HPP

#include <string>


namespace poac::util::ftemplate {
    std::string _gitignore(
        "# The directory Mix downloads your dependencies sources to.\n"
        "./deps/\n"
    );
    std::string main_cpp(
        "#include <iostream>\n"
        "#include <algorithm>\n"
        "\n"
        "#include \"hello_world.hpp\"\n"
        "\n"
        "int main() {\n"
        "    constexpr auto a = hello_world::hello<HWLEN>::world;\n"
        "    std::for_each(a.begin(), a.end(), [](char n) { std::cout << n; });\n"
        "}\n"
    );
    std::string poac_lock(
        "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n"
        "\n"
        "boost:\n"
        "  version: 1.7.0\n"
        "  deps:\n"
        "    - hoge\n"
    );
    std::string poac_yml(
        "# This is a comment.\n"
        "name: sample\n"
        "version: 0.0.1\n"
        "cpp_version: \"\"\n"
        "description: \"This is a Sample file.\"\n"
        "authors:\n"
        "  - \"good author\"\n"
        "license: ISC\n"
        "links:\n"
        "  - GitHub: https://github.com\n"
        "deps:\n"
        "  - hello_world: 1.0.0\n"
    );
    std::string README_md(
        "# PROJECT_NAME\n"
    );
} // end namespace
#endif // !POAC_UTIL_FTEMPLATE_HPP
