#ifndef POAC_UTIL_FTEMPLATE_HPP
#define POAC_UTIL_FTEMPLATE_HPP

#include <string>


namespace poac::util::ftemplate {
    const std::string _gitignore(
        "# The directory poac downloads your dependencies sources to.\n"
        "./deps/\n"
    );
    const std::string main_cpp(
        "#include <iostream>\n"
        "#include <algorithm>\n"
        "\n"
        "#include \"hello_world.hpp\"\n"
        "\n"
        "int main() {\n"
        "    constexpr auto a = hello_world::hello<HWLEN>::world;\n"
        "    std::for_each(a.begin(), a.end(), [](char n) { std::cout << n; });\n"
        "}\n"
    );
    const std::string poac_lock(
        "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n"
        "\n"
        "boost:\n"
        "  version: 1.7.0\n"
        "  deps:\n"
        "    - hoge\n"
    );
    const std::string poac_yml(
        "# Package name\n"
        "name: sample\n"
        "# Package version\n"
        "version: 0.0.1\n"
        "# 98, 03, 11(Include TR1), 14, 17, 20\n"
        "cpp_version: 17\n"
        "# clang or gcc or ICC or MSVC\n"
        "# Specify range of executable version\n"
        "compilers:\n"
        "  clang: \"6 <= v <= 7\"\n"
        "  gcc:   \"7 <= v <= 8\"\n"
        "description: \"This is a sample file.\"\n"
        "# It must be the same as the user name\n"
        "#  of the poac.pm account your created\n"
        "owners:\n"
        "  - main owner\n"
        "license: MIT\n"
        "links:\n"
        "  GitHub: https://github.com/usrname/repository\n"
        "# Describe deps as dependencies\n"
        "# Writing latest will automatically\n"
        "#  fetch the latest package\n"
        "deps:\n"
        "  hello_world: 1.0.0\n"
    );
    const std::string README_md(
        "# PROJECT_NAME\n"
    );
} // end namespace
#endif // !POAC_UTIL_FTEMPLATE_HPP
