#!/bin/bash
#
# Summary: Create a new poacpm project.
# Options: <project-name>
#
set -e

subcommand=${0##*/poac-}
if [[ "$1" == '--help' || "$1" == '-h' ]]; then
	exec "${POAC_ROOT}/libexec/poac---help" $subcommand
elif [[ "$#" != 1 ]]; then
	echo "poac ${subcommand}: illegal option -- $@"
	exec "${POAC_ROOT}/libexec/poac---help" $subcommand
else
	if [[ -d ./$1 ]]; then
		printf "\e[31mThe \"$1\" directory already exists.\e[m\n"
		exit 1
	else
		cp -i -r ${POAC_ROOT}/tmpl ./$1
		echo
		echo "Your \"$1\" project was created successfully."
		echo
		echo
		echo "Go into your project by running:"
		echo "    $ cd $1"
		echo
		echo "Start your project with:"
		echo "    $ poac install hello_world"
		echo "    $ poac run main.cpp"
		echo
	fi
fi
