#!/bin/bash
#
# Summary: Uninstall packages.
# Options: [<pkg-name>]
#
set -e

subcommand=${0##*/poac-}
if [[ "$1" == '--help' || "$1" == '-h' ]]; then
	exec "${POAC_ROOT}/libexec/poac---help" $subcommand
elif [[ "$#" -gt 0 ]]; then
	# TODO: 依存関係の解決はできていない．あと，poac.ymlから書き換える．
	if [[ ! -d ./deps ]]; then
		printf '\e[1;31mdeps directory is not founded!\n'
		echo
		printf '`poac init`などしてインストールして下さい\e[m\n'
		exit 1
	fi
	pkg=("$@")
	for (( i = 0; i < $#; i++ )); do
		if [[ -d ./deps/${pkg[$i]} ]]; then
			rm -rf ./deps/${pkg[$i]}
			printf "\e[1m[$((i+1))/$#] ${pkg[$i]} is deleted\e[m\n"
		else
			printf "\e[1m[$((i+1))/$#]\e[m \e[31m${pkg[$i]} is not founded\e[m\n"
		fi
	done
else
	echo "poac ${subcommand}: illegal option -- $@"
	exec "${POAC_ROOT}/libexec/poac---help" $subcommand
fi
