#ifndef POAC_SUBCMD_INSTALL_HPP
#define POAC_SUBCMD_INSTALL_HPP

#include <iostream>
#include <algorithm>
#include <iterator>
#include <vector>
#include <string>
#include <sstream>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <tuple>
#include <map>
#include <functional>
#include <utility>
#include <tuple>
#include <fstream>
#include <regex>
#include <chrono>

#include <boost/filesystem.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <yaml-cpp/yaml.h>

#include "../io.hpp"
#include "../core/exception.hpp"
#include "../core/resolver.hpp"
#include "../util.hpp"


// Version 1 will allow $ poac install <Nothing> only.
//   Parse poac.yml
// Version 2 will also allow $ poac install [<pkg-names>].
//   Parse arguments.
// TODO: --source (source file only (not pre-built))
namespace poac::subcmd {
    namespace _install {
        // Copy package to ./deps
        bool copy_to_current(const std::string& from, const std::string& to) {
            namespace path = io::file::path;
            const auto from_path = path::poac_cache_dir / from;
            const auto to_path = path::current_deps_dir / to;
            return path::recursive_copy(from_path, to_path);
        }

        void echo_install_status(
                const bool res,
                const std::string& name,
                const std::string& version,
                const std::string& src) {
            const std::string status =
                    name + " " + version + " (from: " + src + ")";
            if (res) { // EXIT_FAILURE
                io::cli::echo(io::cli::to_fetch_failed(status));
            }
            else {
                io::cli::echo(io::cli::to_fetched(status));
            }
        }


        void stream_deps(YAML::Emitter& out, const std::vector<core::resolver::Package>& deps) {
            out << YAML::Key << "dependencies";
            out << YAML::Value << YAML::BeginMap;

            for (const auto& dep : deps) {
                out << YAML::Key << dep.name;
                out << YAML::Value << YAML::BeginMap;

                out << YAML::Key << "version";
                out << YAML::Value << dep.version;

                out << YAML::Key << "source";
                out << YAML::Value << dep.source;

                if (!dep.deps.empty()) {
                    stream_deps(out, dep.deps);
                }
                out << YAML::EndMap;
            }
            out << YAML::EndMap;
        }

        void create_lock_file(const std::size_t& hash, const core::resolver::Resolved& resolved_deps) {
            // Create a poac.lock
            if (std::ofstream ofs("poac.lock"); ofs) {
                ofs << "# Please do not edit this file.\n";
                YAML::Emitter out;
                out << YAML::BeginMap;

                out << YAML::Key << "checksum";
                out << YAML::Value << hash;

                stream_deps(out, resolved_deps.activated);
                ofs << out.c_str() << '\n';
            }
        }


        void fetch_packages(
                const core::resolver::Backtracked& deps,
                const bool quite,
                const bool verbose)
        {
            namespace except = core::exception;
            namespace naming = core::naming;
            namespace path = io::file::path;
            namespace tb = io::file::tarball;
            namespace resolver = core::resolver;

            for (const auto& [name, dep] : deps) {
                const auto cache_name = naming::to_cache(dep.source, name, dep.version);
                const auto current_name = naming::to_current(dep.source, name, dep.version);
                const bool is_cached = resolver::cache::resolve(cache_name);

                if (verbose) {
                    std::cout << "NAME: " << name << "\n"
                              << "  VERSION: " <<  dep.version << "\n"
                              << "  SOURCE: " << dep.source << "\n"
                              << "  CACHE_NAME: " << cache_name << "\n"
                              << "  CURRENT_NAME: " << current_name << "\n"
                              << "  IS_CACHED: " << is_cached << "\n"
                              << std::endl;
                }

                if (is_cached) {
                    const bool res = copy_to_current(cache_name, current_name);
                    if (!quite) {
                        echo_install_status(res, name, dep.version, dep.source);
                    }
                }
                else if (dep.source == "poac") {
                    const auto pkg_dir = path::poac_cache_dir / cache_name;
                    const auto tar_dir = pkg_dir.string() + ".tar.gz";
                    const std::string url = resolver::archive_url(name, dep.version);

                    bool res = io::network::get_file(url, tar_dir);
                    // If res is true, does not execute func. (short-circuit evaluation)
                    res = res || tb::extract_spec_rm(tar_dir, pkg_dir);
                    res = res || copy_to_current(cache_name, current_name);

                    if (!quite) {
                        echo_install_status(res, name, dep.version, dep.source);
                    }
                }
                else if (dep.source == "github") {
                    const auto dest = path::poac_cache_dir / cache_name;
                    const std::string url = resolver::github::archive_url(name);

                    std::map<std::string, std::string> opts;
                    opts.insert(io::network::opt_depth(1));
                    opts.insert(io::network::opt_branch(dep.version));
                    bool res = io::network::clone(url, dest, opts);
                    res = res || copy_to_current(cache_name, current_name);

                    if (!quite) {
                        echo_install_status(res, name, dep.version, dep.source);
                    }
                }
                else {
                    // If called this, it is a bug.
                    throw except::error("Unexcepted error");
                }
            }
        }

        // Depsの形成を行う
        // yaml形式から内部表現へ変換
        // TODO: resolverへ？
        core::resolver::Deps resolve_packages(const YAML::Node& node) {
            namespace except = core::exception;
            namespace naming = core::naming;
            namespace resolver = core::resolver;

            resolver::Deps deps;

            // Even if a package of the same name is written, it is excluded.
            // However, it can not deal with duplication of other information (e.g. version etc.).
            for (const auto& [name, next_node] : node.as<std::map<std::string, YAML::Node>>()) {
                // itr->first: itr->second
                const auto [src, parsed_name] = naming::get_source(name);
                const auto version = naming::get_version(next_node, src);
                const auto current_name = naming::to_current(src, parsed_name, version);

                if (resolver::current::resolve(current_name)) {
                    continue;
                }
                else if (src == "poac" || src == "github") {
                    deps.push_back({ parsed_name, version, src });
                }
                else { // unknown source
                    throw except::error("Unknown source");
                }
            }
            return deps;
        }

        std::size_t get_yaml_hash() {
            // FIXME: ymlのコメント削除しただけで変更と見なされてしまう
            // -> timestampにする or YAML::Loadでコメント無視してからhash
            const std::string yaml_raw = io::file::yaml::load_config_raw();
            return std::hash<std::string>()(yaml_raw);
        }


        template<typename VS, typename = std::enable_if_t<std::is_rvalue_reference_v<VS&&>>>
        void _main(VS&& argv) {
            namespace fs = boost::filesystem;
            namespace except = core::exception;
            namespace path = io::file::path;
            namespace yaml = io::file::yaml;
            namespace cli = io::cli;
            namespace resolver = core::resolver;


            fs::create_directories(path::poac_cache_dir);
            const auto node = yaml::load_config("deps");
            const std::size_t hash = get_yaml_hash();
            const bool quite = util::argparse::use(argv, "-q", "--quite");
            // When used at the same time, --quite is given priority.
            const bool verbose = !quite && util::argparse::use(argv, "-v", "--verbose");


            // TODO: もし，poac.lockが存在して，そこのchecksumが現在の poac.yml のhashと一致しているのなら poac.lock を読んでinstallすれば良い


            // パッケージがキチンと存在するかの解決
            // と，どこに存在するのかの解決 (既にcurrent?, cache? poac? gitub?)
            if (!quite) {
                cli::echo(cli::to_status("Resolving packages..."));
            }
            const resolver::Deps deps = resolve_packages(node.at("deps"));
            if (deps.empty()) {
                throw except::warn("Already up-to-date");
            }


            // 依存関係の解決
            // (依存先のパッケージは，
            //  publish時にpoac.ymlに書いたdepsを保証するため，上の作業をもう一度する必要は無い)
            if (!quite) {
                cli::echo(cli::to_status("Resolving dependencies..."));
            }
            const resolver::Resolved resolved_deps = resolver::resolve(deps);


            if (!quite) {
                cli::echo(cli::to_status("Fetching..."));
                cli::echo();
            }
            fs::create_directories(path::current_deps_dir);
            fetch_packages(resolved_deps.backtracked, quite, verbose);
            if (!quite) {
                cli::echo();
                cli::echo(cli::status_done());
            }

            create_lock_file(hash, resolved_deps);
        }

        void check_arguments(const std::vector<std::string>& argv) {
            namespace except = core::exception;
            if (argv.size() > 1) { // -v OR -q
                throw except::invalid_second_arg("install");
            }
        }
    }

    struct install {
        static const std::string summary() {
            return "Install packages";
        }
        static const std::string options() {
            return "[-v | --verbose, -q | --quite]";
        }
        template<typename VS, typename = std::enable_if_t<std::is_rvalue_reference_v<VS&&>>>
        void operator()(VS&& argv) {
            _install::check_arguments(argv);
            _install::_main(std::move(argv));
        }
    };
} // end namespace
#endif // !POAC_SUBCMD_INSTALL_HPP
