#pragma once

#include "Cmd/Add.hpp"
#include "Cmd/Build.hpp"
#include "Cmd/Clean.hpp"
#include "Cmd/Fmt.hpp"
#include "Cmd/Help.hpp"
#include "Cmd/Init.hpp"
#include "Cmd/Lint.hpp"
#include "Cmd/New.hpp"
#include "Cmd/Run.hpp"
#include "Cmd/Search.hpp"
#include "Cmd/Test.hpp"
#include "Cmd/Tidy.hpp"
#include "Cmd/Version.hpp"
