message(CHECK_START "Finding OpenSSL")
list(APPEND CMAKE_MESSAGE_INDENT "  ")

if (APPLE)
    set(OPENSSL_ROOT_DIR /usr/local/opt/openssl)
endif ()
if (DEFINED OPENSSL_ROOT_DIR)
    set(OPENSSL_LIBRARIES ${OPENSSL_ROOT_DIR}/lib)
endif ()

find_package(OpenSSL REQUIRED)
if (OPENSSL_FOUND)
    message(CHECK_PASS "found")
    if (LINUX)
        list(APPEND OPENSSL_LIBRARIES ssl crypto dl)
    elseif (APPLE)
        list(APPEND OPENSSL_LIBRARIES dl)
    elseif (WIN32)
        list(APPEND OPENSSL_LIBRARIES bcrypt ws2_32)
    endif ()
    message(STATUS "OpenSSL include directory is ... ${OPENSSL_INCLUDE_DIR}")
    message(STATUS "OpenSSL libraries are ... ${OPENSSL_LIBRARIES}")
else ()
    message(CHECK_FAIL "not found")
    list(APPEND missingDependencies openssl)
endif ()

list(POP_BACK CMAKE_MESSAGE_INDENT)
