R"(query searchPackages($name: String!, $limit: Int!, $offset: Int!) @cached(ttl: 600) {
  packages(where: { name : { _like : $name } }, limit: $limit, offset: $offset, distinct_on: name) {
    name
    version
    description
  } packages_aggregate(where: { name : { _like : $name } }) {
    aggregate {
      count(distinct : true)
    }
  }
})"
